click = arguments[0].click();
scrollIntoCenterScript = arguments[0].scrollIntoView({block:'center'});
scrollIntoViewTrue = arguments[0].scrollIntoView(true);
scrollBy = window.scrollBy
scrollToBottom = window.scrollTo(0,document.body.scrollHeight);